import { Box } from "@mui/material";
import Head from "next/head";
import Link from "next/link";
import { FC } from "react";

const Home: FC = () => {
  return (
    <Box>
      <Head>
        <title>Mobile Cover App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="main">Hello world</div>
      <Link href="/dummy">dummy</Link>
    </Box>
  );
};
export default Home;
